/**
 * Where audio bytes live. The rest of the app only sees this interface, so the
 * single-server disk implementation can later be swapped for an object store.
 */
export interface AudioStorage {
  /** Store `data` under `key`, replacing anything there. */
  put(key: string, data: Uint8Array): Promise<void>;
  /** Open for reading; `undefined` if there is no such key. */
  open(key: string): Promise<{ size: number; file: Deno.FsFile } | undefined>;
  /** Remove a key; a missing key is not an error. */
  delete(key: string): Promise<void>;
}

// Keys are generated by the app (hash + extension); refuse anything that could
// leave the directory anyway.
const SAFE_KEY = /^[A-Za-z0-9][A-Za-z0-9._-]*$/;

export class DiskAudioStorage implements AudioStorage {
  /** `dir` may be a function so the location is read when used (tests set it per run). */
  constructor(private dirOrGetter: string | (() => string)) {}

  private get dir(): string {
    return typeof this.dirOrGetter === "function"
      ? this.dirOrGetter()
      : this.dirOrGetter;
  }

  private path(key: string): string {
    if (!SAFE_KEY.test(key)) throw new Error(`unsafe storage key: ${key}`);
    return `${this.dir}/${key}`;
  }

  async put(key: string, data: Uint8Array): Promise<void> {
    const path = this.path(key);
    await Deno.mkdir(this.dir, { recursive: true });
    // Write then rename, so a reader never sees a half-written file.
    const tmp = `${path}.${crypto.randomUUID()}.tmp`;
    try {
      await Deno.writeFile(tmp, data);
      await Deno.rename(tmp, path);
    } catch (err) {
      await Deno.remove(tmp).catch(() => {});
      throw err;
    }
  }

  async open(key: string) {
    const path = this.path(key);
    try {
      const file = await Deno.open(path, { read: true });
      return { size: (await file.stat()).size, file };
    } catch (err) {
      if (err instanceof Deno.errors.NotFound) return undefined;
      throw err;
    }
  }

  async delete(key: string): Promise<void> {
    try {
      await Deno.remove(this.path(key));
    } catch (err) {
      if (!(err instanceof Deno.errors.NotFound)) throw err;
    }
  }
}
